// This file will be automatically generated by the update script
const tools = [
    {
        name: "Interactive Timeline: The Evolution of AI Systems",
        description: "A visual timeline of key breakthroughs, paradigm shifts, and landmark\n          systems that have de...",
        path: "ai-timeline"
    },
    {
        name: "Markdown Table Generator",
        description: "Markdown Output",
        path: "grid-to-md"
    },
    {
        name: "Workout Interval Timer",
        description: "Load a Saved Workout",
        path: "interval-timer"
    },
    {
        name: "Xcode Color Set Explorer",
        description: "Input Color JSON",
        path: "xcode-color-explorer"
    }
];

function renderTools() {
    const toolsGrid = document.getElementById('tools-grid');

    if (tools.length === 0) {
        toolsGrid.innerHTML = '<p class="col-span-full text-center text-gray-500">No tools available yet. Check back soon!</p>';
        return;
    }

    toolsGrid.innerHTML = tools.map(tool => `
        <a href="${tool.path}/" class="block bg-white border border-gray-200 rounded-lg p-6 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-200">
            <h2 class="text-xl font-semibold text-blue-600 mb-2">${tool.name}</h2>
            <p class="text-gray-600">${tool.description}</p>
        </a>
    `).join('');
}

document.addEventListener('DOMContentLoaded', renderTools);